function [ret,x0,str,ts,xts]=comp(t,x,u,flag)
%COMP	is the M-file description of the SIMULINK system named COMP.
%	The block-diagram can be displayed by typing: COMP.
%
%	SYS=COMP(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes COMP to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling COMP with a FLAG of zero:
%	[SIZES]=COMP([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = [mfilename,'_mdl_'];
new_system(sys)
% simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[381,147,1049,505])
     open_system(sys)
end;
set_param(sys,'Solver',        'ode45')
set_param(sys,'StartTime',     '0.0')
set_param(sys,'StopTime',      '5')
set_param(sys,'MinStep',       '0.001')
set_param(sys,'MaxStep',       '0.1')
set_param(sys,'RelTol',        '1e-3')
set_param(sys,'TimeSaveName',  't')
set_param(sys,'StateSaveName', 'x')
set_param(sys,'OutputSaveName','y')
set_param(sys,'SaveTime',      'off')
set_param(sys,'SaveState',     'off')
set_param(sys,'SaveOutput',    'off')

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace3'])
set_param([sys,'/','To Workspace3'],...
		'orientation',1,...
		'VariableName','ey',...
		'buffer','1000000',...
		'position',[445,280,495,300])

add_block('simulink/Continuous/State-Space',[sys,'/','Compensator'])
set_param([sys,'/','Compensator'],...
		'orientation',2,...
		'A','Hhat',...
		'B','Dhat',...
		'C','eye(n-p)',...
		'D','zeros(n-p,p)',...
		'X0','xc0',...
		'position',[425,150,505,190])

add_block('simulink/Signal Routing/Mux',[sys,'/','Mux'])
set_param([sys,'/','Mux'],...
		'orientation',2,...
		'inputs','2',...
		'position',[325,171,350,209])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain2']])
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain Matrix:')
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','S',...
		'position',[255,175,285,205])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain9']])
set_param([sys,'/',['Matrix',13,'Gain9']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain Matrix:')
set_param([sys,'/',['Matrix',13,'Gain9']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','-rho*inv(Lam)',...
		'position',[75,175,105,205])

add_block('simulink/User-Defined Functions/Fcn',[sys,'/','Unv'])
set_param([sys,'/','Unv'],...
		'orientation',2,...
		'Expr','u/(norm(u)+delta)',...
		'MaskDisplay','disp(''UnV'')',...
		'MaskType','unit vector',...
		'MaskPromptString','Unit Vector|delta',...
		'MaskVariables','delta = @1;')
set_param([sys,'/','Unv'],...
		'MaskValueString','u/(norm(u)+delta)',...
		'position',[125,175,165,205])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain10']])
set_param([sys,'/',['Matrix',13,'Gain10']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain10']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','P|',...
		'position',[190,175,220,205])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain3']])
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','L|',...
		'position',[165,245,195,275])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain4']])
set_param([sys,'/',['Matrix',13,'Gain4']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain4']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','T''|',...
		'position',[385,195,415,225])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace8'])
set_param([sys,'/','To Workspace8'],...
		'VariableName','y',...
		'buffer','1000000',...
		'position',[570,100,620,120])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace'])
set_param([sys,'/','To Workspace'],...
		'orientation',2,...
		'VariableName','s',...
		'buffer','1000000',...
		'position',[145,135,195,155])

add_block('simulink/Sources/Clock',[sys,'/','Clock1'])
set_param([sys,'/','Clock1'],...
		'position',[20,300,40,320])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace2'])
set_param([sys,'/','To Workspace2'],...
		'VariableName','t',...
		'buffer','1000000',...
		'position',[90,300,140,320])

add_block('built-in/Sum',[sys,'/','Sum'])
set_param([sys,'/','Sum'],...
		'position',[80,69,100,96])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace4'])
set_param([sys,'/','To Workspace4'],...
		'orientation',3,...
		'VariableName','x',...
		'buffer','1000000',...
		'position',[340,45,390,65])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space'])
set_param([sys,'/','State-Space'],...
		'A','A',...
		'B','B',...
		'C','eye(n)',...
		'D','zeros(n,m)',...
		'X0','x0',...
		'position',[195,64,270,106])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace1'])
set_param([sys,'/','To Workspace1'],...
		'orientation',3,...
		'VariableName','u',...
		'buffer','1000000',...
		'position',[125,35,175,55])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace5'])
set_param([sys,'/','To Workspace5'],...
		'orientation',3,...
		'VariableName','xc',...
		'buffer','1000000',...
		'position',[290,105,340,125])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain5']])
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:',...
		'MaskVariables','K = @1;')
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','C|',...
		'position',[480,70,510,100])
add_line(sys,[275,85;475,85])
add_line(sys,[45,310;85,310])
add_line(sys,[515,85;535,85;535,210;420,210])
add_line(sys,[120,190;110,190])
add_line(sys,[535,170;510,170])
add_line(sys,[470,210;470,275])
add_line(sys,[320,190;290,190])
add_line(sys,[380,210;370,210;370,200;355,200])
add_line(sys,[420,170;370,170;370,180;355,180])
add_line(sys,[312,190;312,260;200,260])
add_line(sys,[250,190;237,190;237,145;200,145])
add_line(sys,[237,190;225,190])
add_line(sys,[185,190;170,190])
add_line(sys,[365,85;365,70])
add_line(sys,[535,110;565,110])
add_line(sys,[160,260;40,260;40,75;75,75])
add_line(sys,[70,190;60,190;60,90;75,90])
add_line(sys,[105,85;190,85])
add_line(sys,[150,85;150,60])
add_line(sys,[391,170;391,143;315,143;315,130])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
