function [ret,x0,str,ts,xts]=obsint(t,x,u,flag)
%OBSINT	is the M-file description of the SIMULINK system named OBSINT.
%	The block-diagram can be displayed by typing: OBSINT.
%
%	SYS=OBSINT(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes OBSINT to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling OBSINT with a FLAG of zero:
%	[SIZES]=OBSINT([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = [mfilename,'_mdl'];
new_system(sys)
% simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[54,121,936,482])
     open_system(sys)
end
set_param(sys,'Solver',        'ode45')
set_param(sys,'StartTime',     '0.0')
set_param(sys,'StopTime',      '7')
set_param(sys,'MinStep',       '0.001')
set_param(sys,'MaxStep',       '0.1')
set_param(sys,'RelTol',        '1e-3')
set_param(sys,'TimeSaveName',  't')
set_param(sys,'StateSaveName', 'x')
set_param(sys,'OutputSaveName','y')
set_param(sys,'SaveTime',      'off')
set_param(sys,'SaveState',     'off')
set_param(sys,'SaveOutput',    'off')


add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain6']])
set_param([sys,'/',['Matrix',13,'Gain6']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain6']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Sr',...
		'position',[365,180,395,210])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain8']])
set_param([sys,'/',['Matrix',13,'Gain8']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain8']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Lr',...
		'position',[300,225,330,255])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain3']])
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Lrdot',...
		'position',[375,270,405,300])

add_block('simulink/Continuous/Derivative',[sys,'/','Derivative'])
set_param([sys,'/','Derivative'],...
		'orientation',2,...
		'position',[445,275,475,295])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace9'])
set_param([sys,'/','To Workspace9'],...
		'orientation',2,...
		'VariableName','s',...
		'buffer','1000000',...
		'position',[95,135,145,155])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain10']])
set_param([sys,'/',['Matrix',13,'Gain10']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain10']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','P',...
		'position',[195,175,225,205])

add_block('built-in/Sum',[sys,'/','Sum1'])
set_param([sys,'/','Sum1'],...
		'orientation',2,...
		'inputs','+-',...
		'position',[245,174,265,201])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain2']])
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','S',...
		'position',[300,135,330,165])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain5']])
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','L',...
		'position',[205,110,235,140])

add_block('built-in/Sum',[sys,'/','Sum2'])
set_param([sys,'/','Sum2'],...
		'orientation',2,...
		'inputs','-+',...
		'position',[530,134,550,161])

add_block('built-in/Integrator',[sys,'/','Integrator'])
set_param([sys,'/','Integrator'],...
		'orientation',2,...
		'position',[480,140,500,160])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain9']])
set_param([sys,'/',['Matrix',13,'Gain9']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain9']],...
        'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).\n',...
        'MaskDescription','-rho*inv(Lam)*norm(Lam)',...
        'MaskValueString','-rho*inv(Lam)*norm(Lam)',...
		'position',[70,175,100,205])

add_block('simulink/User-Defined Functions/Fcn',[sys,'/','UnV'])
set_param([sys,'/','UnV'],...
		'orientation',2,...
		'Expr','u/(norm(u)+delta)',...
		'MaskDisplay','disp(''UnV'')',...
		'MaskType','unit vector',...
		'MaskPromptString','Unit Vector delta',...
		'MaskVariables','delta=@1;')
set_param([sys,'/','UnV'],...
		'MaskValueString','0.001',...
		'position',[120,175,160,205])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain7']])
set_param([sys,'/',['Matrix',13,'Gain7']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain7']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','[zeros(p,n) eye(p); eye(n) zeros(n,p)]')
set_param([sys,'/',['Matrix',13,'Gain7']],...
		'position',[365,110,395,140])

add_block('simulink/Signal Routing/Mux',[sys,'/','Mux'])
set_param([sys,'/','Mux'],...
		'orientation',2,...
		'inputs','2',...
		'position',[425,113,460,162])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace1'])
set_param([sys,'/','To Workspace1'],...
		'VariableName','u',...
		'buffer','1000000',...
		'position',[170,70,220,90])


%     Subsystem  'Observer'.

% new_system([sys,'/','Observer'])
add_block('built-in/SubSystem','obsint_mdl/Observer')
set_param([sys,'/','Observer'],'Location',[363,193,920,525])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain15']])
set_param([sys,'/',['Observer/Matrix',13,'Gain15']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain15']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','F',...
		'position',[190,185,220,215])

add_block('simulink/User-Defined Functions/Fcn',[sys,'/',['Observer/Unv',13,'']])
set_param([sys,'/',['Observer/Unv',13,'']],...
		'Expr','u/(norm(u)+delta)',...
		'MaskDisplay','disp(''UnV'')',...
		'MaskType','unit vector',...
		'MaskPromptString','delta',...
		'MaskVariables','delta=@1;',...
		'MaskValueString','0.01')
set_param([sys,'/',['Observer/Unv',13,'']],...
		'position',[235,185,270,215])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain16']])
set_param([sys,'/',['Observer/Matrix',13,'Gain16']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain16']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','B',...
		'position',[180,35,210,65])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain 4']])
set_param([sys,'/',['Observer/Matrix',13,'Gain 4']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain 4']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','C',...
		'position',[80,120,110,150])

add_block('built-in/Sum',[sys,'/','Observer/Sum4'])
set_param([sys,'/','Observer/Sum4'],...
		'inputs','-+',...
		'position',[130,107,150,143])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain11']])
set_param([sys,'/',['Observer/Matrix',13,'Gain11']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain11']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','-G',...
		'position',[205,110,235,140])

add_block('built-in/Integrator',[sys,'/','Observer/Integrator1'])
set_param([sys,'/','Observer/Integrator1'],...
		'InitialCondition','z0',...
		'position',[435,110,455,130])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain 18']])
set_param([sys,'/',['Observer/Matrix',13,'Gain 18']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain 18']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','A',...
		'position',[420,30,450,60])

add_block('built-in/Sum',[sys,'/','Observer/Sum3'])
set_param([sys,'/','Observer/Sum3'],...
		'inputs','++++',...
		'position',[385,88,405,147])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain14']])
set_param([sys,'/',['Observer/Matrix',13,'Gain14']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain14']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','-rho*eye(m)')
set_param([sys,'/',['Observer/Matrix',13,'Gain14']],...
		'position',[285,185,315,215])

add_block('simulink/Continuous/State-Space',[sys,'/',['Observer/Matrix',13,'Gain13']])
set_param([sys,'/',['Observer/Matrix',13,'Gain13']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Observer/Matrix',13,'Gain13']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','B',...
		'position',[335,128,365,152])

add_block('built-in/Inport',[sys,'/','Observer/in_1'])
set_param([sys,'/','Observer/in_1'],...
		'position',[15,40,35,60])

add_block('built-in/Outport',[sys,'/','Observer/out_1'])
set_param([sys,'/','Observer/out_1'],...
		'orientation',2,...
		'position',[405,185,425,205])

add_block('built-in/Inport',[sys,'/','Observer/in_3'])
set_param([sys,'/','Observer/in_3'],...
		'Port','2',...
		'position',[15,105,35,125])
add_line([sys,'/','Observer'],[155,125;200,125])
add_line([sys,'/','Observer'],[171,125;171,200;185,200])
add_line([sys,'/','Observer'],[460,120;500,120;500,45;455,45])
add_line([sys,'/','Observer'],[491,120;491,246;61,246;61,135;75,135])
add_line([sys,'/','Observer'],[115,135;125,135])
add_line([sys,'/','Observer'],[215,50;245,50;245,110;380,110])
add_line([sys,'/','Observer'],[320,200;330,140])
add_line([sys,'/','Observer'],[225,200;230,200])
add_line([sys,'/','Observer'],[275,200;280,200])
add_line([sys,'/','Observer'],[370,140;380,140])
add_line([sys,'/','Observer'],[240,125;380,125])
add_line([sys,'/','Observer'],[415,45;360,45;360,95;380,95])
add_line([sys,'/','Observer'],[410,120;430,120])
add_line([sys,'/','Observer'],[40,50;175,50])
add_line([sys,'/','Observer'],[40,115;125,115])
add_line([sys,'/','Observer'],[491,195;430,195])


%     Finished composite block 'Observer'.

set_param([sys,'/','Observer'],...
		'orientation',2,...
		'position',[510,45,545,100])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space'])
set_param([sys,'/','State-Space'],...
		'A','A',...
		'B','B',...
		'C','C',...
		'D','zeros(p,m)',...
		'position',[300,4,375,46])

add_block('built-in/Sum',[sys,'/','Sum'])
set_param([sys,'/','Sum'],...
		'inputs','++++',...
		'position',[105,2,125,48])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space2'])
set_param([sys,'/','State-Space2'],...
		'orientation',2,...
		'A','Gamma',...
		'B','Gamma',...
		'C','-eye(p)',...
		'D','zeros(p,p)',...
		'position',[600,175,680,215])

add_block('simulink/Signal Routing/Mux',[sys,'/','Mux2'])
set_param([sys,'/','Mux2'],...
		'orientation',2,...
		'inputs','2',...
		'position',[710,175,745,210])

add_block('simulink/Sources/Step',[sys,'/','step Input1'])
set_param([sys,'/','step Input1'],...
		'orientation',2,...
		'Time','0',...
		'After','0',...
		'position',[815,160,835,180])

add_block('simulink/Sources/Step',[sys,'/','step Input2'])
set_param([sys,'/','step Input2'],...
		'orientation',2,...
		'Time','0',...
		'position',[820,205,840,225])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace2'])
set_param([sys,'/','To Workspace2'],...
		'VariableName','t',...
		'buffer','1000000',...
		'position',[745,65,795,85])

add_block('built-in/Clock',[sys,'/','Clock1'])
set_param([sys,'/','Clock1'],...
		'position',[665,65,685,85])
add_line(sys,[690,75;740,75])
add_line(sys,[115,190;105,190])
add_line(sys,[190,190;165,190])
add_line(sys,[370,285;40,285;40,10;100,10])
add_line(sys,[130,25;295,25])
add_line(sys,[240,190;230,190])
add_line(sys,[295,150;285,150;285,180;270,180])
add_line(sys,[360,195;270,195])
add_line(sys,[65,190;60,190;60,30;100,30])
add_line(sys,[200,125;80,125;80,40;100,40])
add_line(sys,[525,150;505,150])
add_line(sys,[440,285;410,285])
add_line(sys,[295,240;50,240;50,20;100,20])
add_line(sys,[360,125;240,125])
add_line(sys,[349,125;349,150;335,150])
add_line(sys,[475,150;465,150])
add_line(sys,[380,25;600,25;600,140;555,140])
add_line(sys,[182,190;182,145;150,145])
add_line(sys,[141,25;141,80;165,80])
add_line(sys,[420,140;415,140;415,125;400,125])
add_line(sys,[505,75;490,75;490,125;465,125])
add_line(sys,[600,85;550,85])
add_line(sys,[263,25;263,72;438,72;438,32;568,32;568,60;550,60])
add_line(sys,[595,195;400,195])
add_line(sys,[518,195;518,285;480,285])
add_line(sys,[573,195;573,155;555,155])
add_line(sys,[705,195;685,195])
add_line(sys,[810,170;770,170;770,185;750,185])
add_line(sys,[456,195;456,240;335,240])
add_line(sys,[815,215;770,215;770,200;750,200])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
