function [ret,x0,str,ts,xts]=outmod(t,x,u,flag)
%OUTMOD	is the M-file description of the SIMULINK system named OUTMOD.
%	The block-diagram can be displayed by typing: OUTMOD.
%
%	SYS=OUTMOD(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes OUTMOD to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling OUTMOD with a FLAG of zero:
%	[SIZES]=OUTMOD([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = [mfilename,'_mdl_'];
new_system(sys)
% simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[379,264,1052,605])
     open_system(sys)
end;
set_param(sys,'Solver',        'ode45')
set_param(sys,'StartTime',     '0.0')
set_param(sys,'StopTime',      '150')
set_param(sys,'MinStep',       '0.01')
set_param(sys,'MaxStep',       '0.1')
set_param(sys,'RelTol',        '1e-3')
set_param(sys,'TimeSaveName',  't')
set_param(sys,'StateSaveName', 'x')
set_param(sys,'OutputSaveName','y')
set_param(sys,'SaveTime',      'off')
set_param(sys,'SaveState',     'off')
set_param(sys,'SaveOutput',    'off')


add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace1'])
set_param([sys,'/','To Workspace1'],...
		'orientation',3,...
		'VariableName','u',...
		'buffer','1000000',...
		'position',[100,5,150,25])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace2'])
set_param([sys,'/','To Workspace2'],...
		'VariableName','y',...
		'buffer','1000000',...
		'position',[395,75,445,95])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space1'])
set_param([sys,'/','State-Space1'],...
		'orientation',2,...
		'A','Am',...
		'B','Bm',...
		'C','eye(n)',...
		'D','zeros(n,m)',...
		'position',[385,180,465,220])

add_block('built-in/Clock',[sys,'/','Clock'])
set_param([sys,'/','Clock'],...
		'position',[350,5,370,25])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace'])
set_param([sys,'/','To Workspace'],...
		'VariableName','t',...
		'buffer','1000000',...
		'position',[420,7,470,23])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space'])
set_param([sys,'/','State-Space'],...
		'A','A',...
		'B','B',...
		'C','C',...
		'D','zeros(p,m)',...
		'X0','x0',...
		'position',[195,24,270,66])

add_block('built-in/Sum',[sys,'/','Sum 1'])
set_param([sys,'/','Sum 1'],...
		'inputs','+--',...
		'position',[50,27,70,63])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace4'])
set_param([sys,'/','To Workspace4'],...
		'VariableName','ey',...
		'buffer','1000000',...
		'position',[260,85,310,105])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain']])
set_param([sys,'/',['Matrix',13,'Gain']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Cm',...
		'position',[310,150,340,180])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace3'])
set_param([sys,'/','To Workspace3'],...
		'VariableName','ym',...
		'buffer','1000000',...
		'position',[400,135,450,155])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain5']])
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Lr',...
		'position',[310,250,340,280])

add_block('built-in/Sum',[sys,'/','Sum 2'])
set_param([sys,'/','Sum 2'],...
		'orientation',2,...
		'position',[175,207,195,238])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain1']])
set_param([sys,'/',['Matrix',13,'Gain1']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain1']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Lx',...
		'position',[265,200,295,230])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace5'])
set_param([sys,'/','To Workspace5'],...
		'orientation',1,...
		'VariableName','uf',...
		'buffer','1000000',...
		'position',[60,260,110,280])

add_block('simulink/Sources/Step',[sys,'/','Step Input1'])
set_param([sys,'/','Step Input1'],...
		'orientation',2,...
		'Time','0',...
		'After','0',...
		'position',[620,205,640,225])

add_block('built-in/Sum',[sys,'/','Sum 3'])
set_param([sys,'/','Sum 3'],...
		'orientation',2,...
		'inputs','+-',...
		'position',[230,127,250,158])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain4']])
set_param([sys,'/',['Matrix',13,'Gain4']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain4']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','rho*eye(m)',...
		'position',[50,100,80,130])

add_block('simulink/User-Defined Functions/Fcn',[sys,'/','UnV'])
set_param([sys,'/','UnV'],...
		'orientation',2,...
		'Expr','u/(norm(u)+delta)',...
		'MaskDisplay','disp(''UnV'')',...
		'MaskType','unit vector',...
		'MaskPromptString','delta',...
		'MaskVariables','delta=@1;')
set_param([sys,'/','UnV'],...
		'MaskValueString','0.01',...
		'position',[100,100,140,130])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain3']])
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','F',...
		'position',[170,130,200,160])

add_block('simulink/Signal Routing/Mux',[sys,'/','Mux'])
set_param([sys,'/','Mux'],...
		'orientation',2,...
		'inputs','2',...
		'position',[530,182,560,213])

add_block('simulink/Sources/Step',[sys,'/','Step Input'])
set_param([sys,'/','Step Input'],...
		'orientation',2,...
		'Time','0',...
		'position',[620,160,640,180])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain2']])
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','gammac*eye(m)',...
		'position',[75,165,105,195])
add_line(sys,[380,200;360,200;360,165;345,165])
add_line(sys,[275,45;345,45;345,135;255,135])
add_line(sys,[95,115;85,115])
add_line(sys,[225,145;205,145])
add_line(sys,[45,115;35,115;45,55])
add_line(sys,[70,180;25,180;25,45;45,45])
add_line(sys,[260,215;200,215])
add_line(sys,[305,265;240,265;240,230;200,230])
add_line(sys,[170,225;15,225;15,35;45,35])
add_line(sys,[375,15;415,15])
add_line(sys,[75,45;190,45])
add_line(sys,[125,45;125,30])
add_line(sys,[345,85;390,85])
add_line(sys,[305,165;275,165;275,150;255,150])
add_line(sys,[218,145;218,95;255,95])
add_line(sys,[373,200;373,215;300,215])
add_line(sys,[293,165;293,145;395,145])
add_line(sys,[85,225;85,255])
add_line(sys,[615,215;590,215;590,205;565,205])
add_line(sys,[525,200;470,200])
add_line(sys,[615,170;590,170;590,190;565,190])
add_line(sys,[165,145;156,145;156,115;145,115])
add_line(sys,[156,145;156,180;110,180])
add_line(sys,[506,200;506,265;345,265])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
