function [ret,x0,str,ts,xts]=stint(t,x,u,flag)
%STINT	is the M-file description of the SIMULINK system named STINT.
%	The block-diagram can be displayed by typing: STINT.
%
%	SYS=STINT(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes STINT to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling STINT with a FLAG of zero:
%	[SIZES]=STINT([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = [mfilename,'_mdl'];
new_system(sys)
simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[256,348,1068,679])
     open_system(sys)
end;
set_param(sys,'Solver',        'ode45')
set_param(sys,'StartTime',     '0.0')
set_param(sys,'StopTime',      '7')
set_param(sys,'MinStep',       '0.001')
set_param(sys,'MaxStep',       '0.1')
set_param(sys,'RelTol',        '1e-3')
set_param(sys,'TimeSaveName',  't')
set_param(sys,'StateSaveName', 'x')
set_param(sys,'OutputSaveName','y')
set_param(sys,'SaveTime',      'off')
set_param(sys,'SaveState',     'off')
set_param(sys,'SaveOutput',    'off')


add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain6']])
set_param([sys,'/',['Matrix',13,'Gain6']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain6']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Sr|',...
		'position',[365,180,395,210])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain8']])
set_param([sys,'/',['Matrix',13,'Gain8']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain8']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Lr|',...
		'position',[300,225,330,255])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain3']])
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain3']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','Lrdot|',...
		'position',[375,270,405,300])

add_block('simulink/Continuous/Derivative',[sys,'/','Derivative'])
set_param([sys,'/','Derivative'],...
		'orientation',2,...
		'position',[445,275,475,295])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace3'])
set_param([sys,'/','To Workspace3'],...
		'VariableName','x',...
		'buffer','1000000',...
		'position',[410,15,460,35])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace1'])
set_param([sys,'/','To Workspace1'],...
		'VariableName','u',...
		'buffer','1000000',...
		'position',[205,5,255,25])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space'])
set_param([sys,'/','State-Space'],...
		'A','A',...
		'B','B',...
		'C','eye(n)',...
		'D','zeros(n,m)',...
		'position',[250,54,325,96])

add_block('built-in/Sum',[sys,'/','Sum'])
set_param([sys,'/','Sum'],...
		'inputs','++++',...
		'position',[105,52,125,98])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace9'])
set_param([sys,'/','To Workspace9'],...
		'orientation',2,...
		'VariableName','s',...
		'buffer','1000000',...
		'position',[95,135,145,155])

add_block('simulink/Continuous/State-Space',[sys,'/','State-Space1'])
set_param([sys,'/','State-Space1'],...
		'orientation',2,...
		'A','Gamma',...
		'B','Gamma',...
		'C','-eye(p)',...
		'D','zeros(p,p)',...
		'position',[580,176,655,214])

add_block('simulink/Signal Routing/Mux',[sys,'/','Mux2'])
set_param([sys,'/','Mux2'],...
		'orientation',2,...
		'inputs','2',...
		'position',[675,177,705,208])

add_block('built-in/Sum',[sys,'/','Sum1'])
set_param([sys,'/','Sum1'],...
		'orientation',2,...
		'inputs','+-',...
		'position',[245,174,265,201])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain2']])
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain2']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','S|',...
		'position',[300,135,330,165])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain7']])
set_param([sys,'/',['Matrix',13,'Gain7']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain7']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','[zeros(p,n) eye(p); eye(n) zeros(n,p)] |')
set_param([sys,'/',['Matrix',13,'Gain7']],...
		'position',[370,110,400,140])

add_block('simulink/Signal Routing/Mux',[sys,'/','Mux'])
set_param([sys,'/','Mux'],...
		'orientation',2,...
		'inputs','2',...
		'position',[420,105,455,140])

add_block('built-in/Sum',[sys,'/','Sum2'])
set_param([sys,'/','Sum2'],...
		'orientation',2,...
		'inputs','-+',...
		'position',[530,134,550,161])

add_block('built-in/Integrator',[sys,'/','Integrator'])
set_param([sys,'/','Integrator'],...
		'orientation',2,...
		'position',[480,140,500,160])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain12']])
set_param([sys,'/',['Matrix',13,'Gain12']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:',...
		'MaskVariables','K = @1;')
set_param([sys,'/',['Matrix',13,'Gain12']],...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','C|',...
		'position',[510,60,540,90])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace8'])
set_param([sys,'/','To Workspace8'],...
		'VariableName','y',...
		'buffer','1000000',...
		'position',[635,95,685,115])

add_block('simulink/Sources/Step',[sys,'/','Step Input1'])
set_param([sys,'/','Step Input1'],...
		'orientation',2,...
		'Time','0',...
		'After','0',...
		'position',[760,160,780,180])

add_block('simulink/Sources/Step',[sys,'/','Step Input2'])
set_param([sys,'/','Step Input2'],...
		'orientation',2,...
		'Time','0',...
		'position',[760,200,780,220])

add_block('built-in/Clock',[sys,'/','Clock1'])
set_param([sys,'/','Clock1'],...
		'position',[570,15,590,35])

add_block('simulink/Sinks/To Workspace',[sys,'/','To Workspace2'])
set_param([sys,'/','To Workspace2'],...
		'VariableName','t',...
		'buffer','1000000',...
		'position',[650,15,700,35])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain9']])
set_param([sys,'/',['Matrix',13,'Gain9']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain9']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','-rho*inv(Lam)|',...
		'position',[70,175,100,205])

add_block('simulink/User-Defined Functions/Fcn',[sys,'/','UnV'])
set_param([sys,'/','UnV'],...
		'orientation',2,...
		'Expr','u/(norm(u)+delta)',...
		'MaskDisplay','disp(''UnV'')',...
		'MaskType','unit vector',...
		'MaskPromptString','Unit Vector|delta',...
		'MaskVariables','delta=@1;')
set_param([sys,'/','UnV'],...
		'MaskValueString','0.001|',...
		'position',[120,175,160,205])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain10']])
set_param([sys,'/',['Matrix',13,'Gain10']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain10']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','P|',...
		'position',[200,175,230,205])

add_block('simulink/Continuous/State-Space',[sys,'/',['Matrix',13,'Gain5']])
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'orientation',2,...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'MaskDisplay','disp(''K'')',...
		'MaskType','Matrix Gain',...
		'MaskPromptString','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Matrix',13,'Gain5']],...
		'MaskVariables','K = @1;',...
		'MaskHelp','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'MaskValueString','L|',...
		'position',[210,110,240,140])
add_line(sys,[595,25;645,25])
add_line(sys,[115,190;105,190])
add_line(sys,[195,190;165,190])
add_line(sys,[370,285;40,285;40,60;100,60])
add_line(sys,[130,75;245,75])
add_line(sys,[156,75;156,15;200,15])
add_line(sys,[240,190;235,190])
add_line(sys,[295,150;285,150;285,180;270,180])
add_line(sys,[360,195;270,195])
add_line(sys,[65,190;60,190;60,80;100,80])
add_line(sys,[205,125;80,125;80,90;100,90])
add_line(sys,[525,150;505,150])
add_line(sys,[575,195;400,195])
add_line(sys,[440,285;410,285])
add_line(sys,[295,240;50,240;50,70;100,70])
add_line(sys,[451,195;451,240;335,240])
add_line(sys,[566,195;566,155;555,155])
add_line(sys,[501,195;501,285;480,285])
add_line(sys,[670,195;660,195])
add_line(sys,[755,170;730,170;730,185;710,185])
add_line(sys,[755,210;730,210;730,200;710,200])
add_line(sys,[415,125;405,125])
add_line(sys,[365,125;245,125])
add_line(sys,[349,125;349,150;335,150])
add_line(sys,[475,150;475,130;460,130])
add_line(sys,[330,75;505,75])
add_line(sys,[484,75;484,115;460,115])
add_line(sys,[545,75;585,75;585,140;555,140])
add_line(sys,[585,105;630,105])
add_line(sys,[374,75;374,25;405,25])
add_line(sys,[179,190;179,145;150,145])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
